version: 2.1

jobs:
  build:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            set -e
            python --version
            python -m pip install --upgrade pip setuptools wheel
            pip install build
            pip install .[test]
            python -c "
            import sys, subprocess
            if sys.version_info < (3, 12):
                subprocess.check_call(['pip', 'install', '.[mip]'])
            "
      - run:
          name: Install pandoc
          command: |
            sudo apt-get update
            sudo apt-get install -y pandoc
      - run:
          name: Build documentation
          command: |
            cd docs
            make html
      - run:
          name: Run tests
          command: |
            pytest odtlearn/tests -v

workflows:
  build-and-test:
    jobs:
      - build:
          matrix:
            parameters:
              python-version: ["3.9", "3.11", "3.13", "3.14"]
