version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m pip install --upgrade pip setuptools wheel
            pwd
            pip install -r requirements.txt
            pip install .
      - run:
          name: install pandoc
          command: |
            sudo apt-get update
            sudo apt-get install -y pandoc
      - run:
          name: Build Documentation
          command: |
            cd docs
            make html
      - store_artifacts:
          path: docs/_build/html/
          destination: docs
      - store_artifacts:
          path: ~/log.txt
      - run: ls -ltrh docs/_build/html
    filters:
      branches:
        ignore: gh-pages

workflows:
  version: 2
  workflow:
    jobs:
      - build
